config-version: 1

ping:
  enabled: true
  allow-dm: true
  cooldown: 1000 # In milliseconds
  buttons:
    pingAgain:
      enabled: true
      allow-dm: true
      show-button-if-disabled: false
      cooldown: 2000

su:
  enabled: true
  allow-dm: true
  cooldown: 0

sync-settings:
  enabled: true
  allow-dm: true
  cooldown: 0
  subcommands:
    configs:
      enabled: true
      allow-dm: true
      cooldown: 0
      su-only: true
