config-version: 1

ping:
  enabled: true
  allow-dm: true
  cooldown: 1000 # In milliseconds
  buttons:
    pingAgain:
      enabled: false
      allow-dm: true
      show-button-if-disabled: false
      cooldown: 3000
